---
services:
  wot_recruit_bot:
    build: ./
    image: wot_bot
    volumes:
      - ${PWD}/wot.csv:/app/wot.csv
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      APPLICATION_ID: ${APPLICATION_ID}
      DATAFILE: ${DATAFILE}
      WOT_RATE_LIMIT: ${WOT_RATE_LIMIT}
      DISCORD_LOGGING_WEBHOOK: ${DISCORD_LOGGING_WEBHOOK}
      DISCORD_RECRUITMENT_WEBHOOK: ${DISCORD_RECRUITMENT_WEBHOOK}